command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--https-port=8443"
  - "--https-certificate-file=/etc/tls/tls.crt"
  - "--https-certificate-key-file=/etc/tls/tls.key"
  - "--hostname=${hostname}"
  - "--hostname-strict=true"
  - "--metrics-enabled=true"
  - "--health-enabled=true"

image:
  tag: "26.0.6"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: user
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:MaxRAMPercentage=50.0
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: keycloak-db-postgresql
  port: 5432
  username: dbusername
  password: dbpassword
  database: keycloak

secrets:
  admin-creds:
    annotations:
      my-test-annotation: Test secret for {{ include "keycloak.fullname" . }}
    stringData:
      user: admin
      password: secret

extraInitContainers: |
  - name: theme-downloader
    image: curlimages/curl
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -c
      - |
        echo "Downloading Keycloak theme JAR..."
        curl -L -f -S -o /extensions/keycloak-theme.jar "https://trustorbstfstate2025.blob.core.windows.net/keycloak-themes/keycloak-theme.jar?se=2025-12-31T23%3A59%3A59Z&sp=r&sv=2022-11-02&sr=b&sig=2%2FB%2FZXo3rNb7rh0SzN0tQVd84kiNHmBBmd7sAcyK5dc%3D"
    volumeMounts:
      - name: extensions
        mountPath: /extensions

extraVolumes: |
  - name: extensions
    emptyDir: {}

  - name: tls-volume
    secret:
      secretName: trustorbs-tls

extraVolumeMounts: |
  - name: extensions
    mountPath: /opt/keycloak/providers

  - name: tls-volume
    mountPath: /etc/tls
    readOnly: true

livenessProbe: |
  httpGet:
    path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/health/live'
    port: 9000
    scheme: HTTPS
  initialDelaySeconds: 0
  timeoutSeconds: 5

readinessProbe: |
  httpGet:
    path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/health/ready'
    port: 9000
    scheme: HTTPS
  initialDelaySeconds: 10
  timeoutSeconds: 1

startupProbe: |
  httpGet:
    path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/health'
    port: 9000
    scheme: HTTPS
  initialDelaySeconds: 15
  timeoutSeconds: 1
  failureThreshold: 60
  periodSeconds: 5

# Add metrics configuration
metrics:
  enabled: true
